// Real median property tax rates, insurance rates, and state income tax rates by state
export const STATE_DATA: Record<string, { label: string; propertyTax: number; insurance: number; stateTax: number }> = {
  '': { label: 'Select a state…', propertyTax: 1.35, insurance: 0.55, stateTax: 0 },
  AL: { label: 'Alabama', propertyTax: 0.41, insurance: 0.77, stateTax: 5 },
  AK: { label: 'Alaska', propertyTax: 1.19, insurance: 0.70, stateTax: 0 },
  AZ: { label: 'Arizona', propertyTax: 0.62, insurance: 0.52, stateTax: 2.5 },
  AR: { label: 'Arkansas', propertyTax: 0.62, insurance: 0.76, stateTax: 4.4 },
  CA: { label: 'California', propertyTax: 0.74, insurance: 0.47, stateTax: 9.3 },
  CO: { label: 'Colorado', propertyTax: 0.51, insurance: 0.65, stateTax: 4.4 },
  CT: { label: 'Connecticut', propertyTax: 2.14, insurance: 0.52, stateTax: 5 },
  DE: { label: 'Delaware', propertyTax: 0.57, insurance: 0.38, stateTax: 5.5 },
  DC: { label: 'Washington D.C.', propertyTax: 0.56, insurance: 0.40, stateTax: 6 },
  FL: { label: 'Florida', propertyTax: 0.89, insurance: 1.55, stateTax: 0 },
  GA: { label: 'Georgia', propertyTax: 0.92, insurance: 0.60, stateTax: 5.49 },
  HI: { label: 'Hawaii', propertyTax: 0.28, insurance: 0.35, stateTax: 7.2 },
  ID: { label: 'Idaho', propertyTax: 0.69, insurance: 0.44, stateTax: 5.8 },
  IL: { label: 'Illinois', propertyTax: 2.27, insurance: 0.52, stateTax: 4.95 },
  IN: { label: 'Indiana', propertyTax: 0.85, insurance: 0.46, stateTax: 3.15 },
  IA: { label: 'Iowa', propertyTax: 1.57, insurance: 0.48, stateTax: 5.7 },
  KS: { label: 'Kansas', propertyTax: 1.41, insurance: 0.73, stateTax: 5.7 },
  KY: { label: 'Kentucky', propertyTax: 0.86, insurance: 0.55, stateTax: 4.5 },
  LA: { label: 'Louisiana', propertyTax: 0.55, insurance: 1.30, stateTax: 4.25 },
  ME: { label: 'Maine', propertyTax: 1.36, insurance: 0.42, stateTax: 7.15 },
  MD: { label: 'Maryland', propertyTax: 1.09, insurance: 0.45, stateTax: 5 },
  MA: { label: 'Massachusetts', propertyTax: 1.23, insurance: 0.48, stateTax: 5 },
  MI: { label: 'Michigan', propertyTax: 1.54, insurance: 0.50, stateTax: 4.25 },
  MN: { label: 'Minnesota', propertyTax: 1.12, insurance: 0.53, stateTax: 7.05 },
  MS: { label: 'Mississippi', propertyTax: 0.81, insurance: 0.88, stateTax: 5 },
  MO: { label: 'Missouri', propertyTax: 0.97, insurance: 0.66, stateTax: 4.95 },
  MT: { label: 'Montana', propertyTax: 0.84, insurance: 0.55, stateTax: 5.9 },
  NE: { label: 'Nebraska', propertyTax: 1.73, insurance: 0.62, stateTax: 5.84 },
  NV: { label: 'Nevada', propertyTax: 0.60, insurance: 0.46, stateTax: 0 },
  NH: { label: 'New Hampshire', propertyTax: 2.18, insurance: 0.42, stateTax: 0 },
  NJ: { label: 'New Jersey', propertyTax: 2.49, insurance: 0.42, stateTax: 6.37 },
  NM: { label: 'New Mexico', propertyTax: 0.80, insurance: 0.55, stateTax: 4.9 },
  NY: { label: 'New York', propertyTax: 1.72, insurance: 0.48, stateTax: 6.85 },
  NC: { label: 'North Carolina', propertyTax: 0.84, insurance: 0.50, stateTax: 4.5 },
  ND: { label: 'North Dakota', propertyTax: 0.98, insurance: 0.55, stateTax: 1.95 },
  OH: { label: 'Ohio', propertyTax: 1.56, insurance: 0.44, stateTax: 3.5 },
  OK: { label: 'Oklahoma', propertyTax: 0.90, insurance: 1.05, stateTax: 4.75 },
  OR: { label: 'Oregon', propertyTax: 0.97, insurance: 0.38, stateTax: 8.75 },
  PA: { label: 'Pennsylvania', propertyTax: 1.58, insurance: 0.38, stateTax: 3.07 },
  RI: { label: 'Rhode Island', propertyTax: 1.63, insurance: 0.50, stateTax: 4.75 },
  SC: { label: 'South Carolina', propertyTax: 0.57, insurance: 0.68, stateTax: 6.4 },
  SD: { label: 'South Dakota', propertyTax: 1.31, insurance: 0.55, stateTax: 0 },
  TN: { label: 'Tennessee', propertyTax: 0.71, insurance: 0.62, stateTax: 0 },
  TX: { label: 'Texas', propertyTax: 1.80, insurance: 1.05, stateTax: 0 },
  UT: { label: 'Utah', propertyTax: 0.63, insurance: 0.40, stateTax: 4.65 },
  VT: { label: 'Vermont', propertyTax: 1.90, insurance: 0.40, stateTax: 6.6 },
  VA: { label: 'Virginia', propertyTax: 0.82, insurance: 0.40, stateTax: 5.75 },
  WA: { label: 'Washington', propertyTax: 1.03, insurance: 0.42, stateTax: 0 },
  WV: { label: 'West Virginia', propertyTax: 0.58, insurance: 0.55, stateTax: 5.12 },
  WI: { label: 'Wisconsin', propertyTax: 1.85, insurance: 0.40, stateTax: 5.3 },
  WY: { label: 'Wyoming', propertyTax: 0.61, insurance: 0.55, stateTax: 0 },
};
