import { useCallback } from 'react';
import { Printer } from 'lucide-react';
import { Button } from '@/components/ui/button';

interface PrintSection {
  label: string;
  value: string;
  highlight?: boolean;
}

interface CalculatorPrintViewProps {
  calculatorType: string;
  inputs: { label: string; value: string }[];
  results: PrintSection[];
  notes?: string;
}

const CALC_TITLES: Record<string, string> = {
  mortgage: 'Mortgage Calculator',
  auto: 'Auto Loan Calculator',
  creditcard: 'Credit Card Payoff',
  credit: 'Credit Card Payoff',
  investment: 'Investment Calculator',
  debt: 'General Debt Calculator',
  wealth: 'Wealth Multiplier',
  offers: 'Focus Offer Calculator',
};

export default function CalculatorPrintView({ calculatorType, inputs, results, notes }: CalculatorPrintViewProps) {
  const handlePrint = useCallback(() => {
    const title = CALC_TITLES[calculatorType] || 'Calculator Results';
    const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' });

    const inputRows = inputs.map(i => `
      <tr>
        <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;color:#6b7280;font-size:13px;width:40%">${i.label}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;font-weight:600;font-size:13px">${i.value}</td>
      </tr>
    `).join('');

    const resultCards = results.map(r => `
      <div style="flex:1;min-width:140px;padding:14px 16px;border-radius:10px;${r.highlight ? 'background:linear-gradient(135deg,#6366f115,#8b5cf615);border:1px solid #6366f130' : 'background:#f9fafb;border:1px solid #e5e7eb'}">
        <div style="font-size:11px;text-transform:uppercase;letter-spacing:0.05em;color:#6b7280;margin-bottom:4px">${r.label}</div>
        <div style="font-size:20px;font-weight:700;${r.highlight ? 'color:#6366f1' : 'color:#111827'}">${r.value}</div>
      </div>
    `).join('');

    const notesSection = notes ? `
      <div style="margin-top:24px;padding:16px;background:#f0fdf4;border:1px solid #bbf7d0;border-radius:10px">
        <div style="font-size:11px;text-transform:uppercase;letter-spacing:0.05em;color:#16a34a;font-weight:600;margin-bottom:6px">📝 Notes</div>
        <div style="font-size:13px;color:#374151;line-height:1.6">${notes}</div>
      </div>
    ` : '';

    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${title} — PrismMoney</title>
  <style>
    @page { size: letter; margin: 0.75in; }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #111827; line-height: 1.5; }
    @media print {
      body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    }
  </style>
</head>
<body>
  <div style="max-width:680px;margin:0 auto">
    <!-- Header -->
    <div style="display:flex;justify-content:space-between;align-items:flex-end;border-bottom:3px solid #6366f1;padding-bottom:12px;margin-bottom:28px">
      <div>
        <div style="font-size:11px;text-transform:uppercase;letter-spacing:0.1em;color:#6366f1;font-weight:600;margin-bottom:2px">PrismMoney</div>
        <h1 style="font-size:24px;font-weight:700;color:#111827">${title}</h1>
      </div>
      <div style="font-size:12px;color:#9ca3af;text-align:right">
        Generated<br/>${now}
      </div>
    </div>

    <!-- Inputs -->
    <div style="margin-bottom:28px">
      <h2 style="font-size:13px;text-transform:uppercase;letter-spacing:0.06em;color:#6366f1;font-weight:600;margin-bottom:10px">Inputs</h2>
      <table style="width:100%;border-collapse:collapse;border:1px solid #e5e7eb;border-radius:8px;overflow:hidden">
        ${inputRows}
      </table>
    </div>

    <!-- Results -->
    <div style="margin-bottom:28px">
      <h2 style="font-size:13px;text-transform:uppercase;letter-spacing:0.06em;color:#6366f1;font-weight:600;margin-bottom:10px">Results</h2>
      <div style="display:flex;gap:12px;flex-wrap:wrap">
        ${resultCards}
      </div>
    </div>

    ${notesSection}

    <!-- Footer -->
    <div style="margin-top:40px;padding-top:12px;border-top:1px solid #e5e7eb;font-size:11px;color:#9ca3af;display:flex;justify-content:space-between">
      <span>Generated by PrismMoney Financial Calculators</span>
      <span>For personal financial planning only — not financial advice</span>
    </div>
  </div>
</body>
</html>`;

    const printWindow = window.open('', '_blank', 'width=800,height=900');
    if (!printWindow) return;
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 300);
  }, [calculatorType, inputs, results, notes]);

  return (
    <Button variant="outline" size="sm" onClick={handlePrint} className="gap-1.5 text-xs">
      <Printer className="h-3.5 w-3.5" />
      Print
    </Button>
  );
}
