insert into public.se_market_symbols (symbol, name, asset_type) values
('VOO','Vanguard S&P 500 ETF','etf'),('VTI','Vanguard Total Stock Market ETF','etf'),('IVV','iShares Core S&P 500 ETF','etf'),
('SPMO','Invesco S&P 500 Momentum ETF','etf'),('MTUM','iShares MSCI USA Momentum Factor ETF','etf'),('QUAL','iShares MSCI USA Quality Factor ETF','etf'),
('VTV','Vanguard Value ETF','etf'),('VUG','Vanguard Growth ETF','etf'),('SCHD','Schwab US Dividend Equity ETF','etf'),('DGRO','iShares Core Dividend Growth ETF','etf'),
('VYM','Vanguard High Dividend Yield ETF','etf'),('RSP','Invesco S&P 500 Equal Weight ETF','etf'),('SPLG','SPDR Portfolio S&P 500 ETF','etf'),
('IAU','iShares Gold Trust','etf'),('GLD','SPDR Gold Shares','etf'),('SLV','iShares Silver Trust','etf'),('GDX','VanEck Gold Miners ETF','etf'),
('QTUM','Defiance Quantum ETF','etf'),('ITA','iShares US Aerospace & Defense ETF','etf'),('XAR','SPDR S&P Aerospace & Defense ETF','etf'),
('SMH','VanEck Semiconductor ETF','etf'),('SOXX','iShares Semiconductor ETF','etf'),('IGV','iShares Expanded Tech-Software ETF','etf'),
('XLI','Industrial Select Sector SPDR','etf'),('XLY','Consumer Discretionary Select Sector SPDR','etf'),('XLP','Consumer Staples Select Sector SPDR','etf'),
('XLU','Utilities Select Sector SPDR','etf'),('XLB','Materials Select Sector SPDR','etf'),('XLRE','Real Estate Select Sector SPDR','etf'),
('XLC','Communication Services Select Sector SPDR','etf'),('XBI','SPDR S&P Biotech ETF','etf'),('IBB','iShares Biotechnology ETF','etf'),
('KRE','SPDR S&P Regional Banking ETF','etf'),('XOP','SPDR S&P Oil & Gas Exploration ETF','etf'),('XME','SPDR S&P Metals & Mining ETF','etf'),
('ITB','iShares US Home Construction ETF','etf'),('JETS','US Global Jets ETF','etf'),('TAN','Invesco Solar ETF','etf'),('ICLN','iShares Global Clean Energy ETF','etf'),
('ARKK','ARK Innovation ETF','etf'),('IWF','iShares Russell 1000 Growth ETF','etf'),('IWD','iShares Russell 1000 Value ETF','etf'),
('IJH','iShares Core S&P Mid-Cap ETF','etf'),('IJR','iShares Core S&P Small-Cap ETF','etf'),('MDY','SPDR S&P Midcap 400 ETF','etf'),
('EFA','iShares MSCI EAFE ETF','etf'),('EEM','iShares MSCI Emerging Markets ETF','etf'),('VEA','Vanguard FTSE Developed Markets ETF','etf'),
('VWO','Vanguard FTSE Emerging Markets ETF','etf'),('IEFA','iShares Core MSCI EAFE ETF','etf'),('VXUS','Vanguard Total International Stock ETF','etf'),
('EWJ','iShares MSCI Japan ETF','etf'),('FXI','iShares China Large-Cap ETF','etf'),('INDA','iShares MSCI India ETF','etf'),('EWZ','iShares MSCI Brazil ETF','etf'),
('AGG','iShares Core US Aggregate Bond ETF','etf'),('BND','Vanguard Total Bond Market ETF','etf'),('TLT','iShares 20+ Year Treasury Bond ETF','etf'),
('IEF','iShares 7-10 Year Treasury Bond ETF','etf'),('SHY','iShares 1-3 Year Treasury Bond ETF','etf'),('LQD','iShares Investment Grade Corporate Bond ETF','etf'),
('HYG','iShares High Yield Corporate Bond ETF','etf'),('TIP','iShares TIPS Bond ETF','etf'),('BIL','SPDR 1-3 Month T-Bill ETF','etf'),
('SGOV','iShares 0-3 Month Treasury Bond ETF','etf'),('VNQ','Vanguard Real Estate ETF','etf'),('SCHH','Schwab US REIT ETF','etf'),
('DBC','Invesco DB Commodity Index Fund','etf'),('USO','United States Oil Fund','etf'),('UNG','United States Natural Gas Fund','etf'),
('VIG','Vanguard Dividend Appreciation ETF','etf'),('MOAT','VanEck Morningstar Wide Moat ETF','etf'),('COWZ','Pacer US Cash Cows 100 ETF','etf'),
('QQQM','Invesco Nasdaq 100 ETF','etf'),('VGT','Vanguard Information Technology ETF','etf'),('FTEC','Fidelity MSCI Information Technology ETF','etf'),
('IBIT','iShares Bitcoin Trust','etf'),('FBTC','Fidelity Wise Origin Bitcoin Fund','etf'),('BITO','ProShares Bitcoin Strategy ETF','etf'),
('AVGO','Broadcom Inc','stock'),('LLY','Eli Lilly and Company','stock'),('XOM','Exxon Mobil Corporation','stock'),('CVX','Chevron Corporation','stock'),
('KO','Coca-Cola Company','stock'),('PEP','PepsiCo Inc','stock'),('MCD','McDonald''s Corporation','stock'),('NKE','NIKE Inc','stock'),
('CRM','Salesforce Inc','stock'),('ADBE','Adobe Inc','stock'),('ORCL','Oracle Corporation','stock'),('NFLX','Netflix Inc','stock'),
('INTC','Intel Corporation','stock'),('QCOM','QUALCOMM Inc','stock'),('TXN','Texas Instruments Inc','stock'),('MU','Micron Technology Inc','stock'),
('CAT','Caterpillar Inc','stock'),('BA','Boeing Company','stock'),('GE','GE Aerospace','stock'),('LMT','Lockheed Martin Corporation','stock'),
('RTX','RTX Corporation','stock'),('ABBV','AbbVie Inc','stock'),('MRK','Merck & Co Inc','stock'),('PFE','Pfizer Inc','stock'),
('TMO','Thermo Fisher Scientific Inc','stock'),('ABT','Abbott Laboratories','stock'),('LOW','Lowe''s Companies Inc','stock'),
('TGT','Target Corporation','stock'),('SBUX','Starbucks Corporation','stock'),('GS','Goldman Sachs Group Inc','stock'),
('MS','Morgan Stanley','stock'),('WFC','Wells Fargo & Company','stock'),('AXP','American Express Company','stock'),('MA','Mastercard Inc','stock'),
('T','AT&T Inc','stock'),('VZ','Verizon Communications Inc','stock'),('CSCO','Cisco Systems Inc','stock'),('IBM','International Business Machines','stock'),
('UBER','Uber Technologies Inc','stock'),('PLTR','Palantir Technologies Inc','stock'),('SHOP','Shopify Inc','stock'),('COIN','Coinbase Global Inc','stock')
on conflict (symbol) do update set asset_type = excluded.asset_type, name = excluded.name;